=== Durengo/durlibjava/domain-hibernate-mapped/src/main/resources/Airport.dtd
<!ELEMENT airport (airport_id, airport_name, airport_size, airport_latitude, airport_longitude, airport_country, airport_city, airport_traffic_control_tower, airplanes)>
	<!ELEMENT airport_id (#PCDATA)>
	<!ELEMENT airport_name (#PCDATA)>
	<!ELEMENT airport_size (#PCDATA)>
		<!ATTLIST airport_size type (SmallAirport | MediumAirport | LargeAirport) "SmallAirport">
	<!ELEMENT airport_latitude (#PCDATA)>
	<!ELEMENT airport_longitude (#PCDATA)>
	<!ELEMENT airport_country (#PCDATA)>
	<!ELEMENT airport_city (#PCDATA)>
	<!ELEMENT airport_traffic_control_tower (traffic_control_tower_id, traffic_control_tower_airspace, traffic_control_tower_runways, traffic_control_tower_telemetries, traffic_control_tower_control_tower_operators)>
		<!ELEMENT traffic_control_tower_id (#PCDATA)>
		<!ELEMENT traffic_control_tower_airspace (airspace_id, airspace_radius, airspace_airspace_class, airspace_airplanes_in_vicinity)>
			<!ELEMENT airspace_id (#PCDATA)>
			<!ELEMENT airspace_radius (#PCDATA)>
			<!ELEMENT airspace_airspace_class (#PCDATA)>
				<!ATTLIST airspace_airspace_class type (ClassAlpha | ClassBravo | ClassCharlie | ClassDelta) "ClassAlpha">
			<!ELEMENT airspace_airplanes_in_vicinity (#PCDATA)>
		<!ELEMENT traffic_control_tower_runways (traffic_control_tower_runway+)>
			<!ELEMENT traffic_control_tower_runway (runway_id, runway_length, runway_width)>
				<!ELEMENT runway_id (#PCDATA)>
				<!ELEMENT runway_length (#PCDATA)>
				<!ELEMENT runway_width (#PCDATA)>
		<!ELEMENT traffic_control_tower_telemetries (traffic_control_tower_telemetry*)>
			<!ELEMENT traffic_control_tower_telemetry (telemetry_id, telemetry_date_time, telemetry_area, telemetry_temperature, telemetry_wind_speed, telemetry_humidity, telemetry_local_atmospheric_pressure)>
				<!ELEMENT telemetry_id (#PCDATA)>
				<!ELEMENT telemetry_date_time (#PCDATA)>
				<!ELEMENT telemetry_area (#PCDATA)>
				<!ELEMENT telemetry_temperature (#PCDATA)>
				<!ELEMENT telemetry_wind_speed (#PCDATA)>
				<!ELEMENT telemetry_humidity (#PCDATA)>
				<!ELEMENT telemetry_local_atmospheric_pressure (#PCDATA)>
		<!ELEMENT traffic_control_tower_control_tower_operators (traffic_control_tower_control_tower_operator*)>
			<!ELEMENT traffic_control_tower_control_tower_operator (person_id, person_first_name, person_last_name, person_date_of_birth, person_age, person_weight)>
				<!ELEMENT person_id (#PCDATA)>
				<!ELEMENT person_first_name (#PCDATA)>
				<!ELEMENT person_last_name (#PCDATA)>
				<!ELEMENT person_date_of_birth (#PCDATA)>
				<!ELEMENT person_age (#PCDATA)>
				<!ELEMENT person_weight (#PCDATA)>
	<!ELEMENT airplanes (airplane*)>
		<!ELEMENT airplane (airplane_id, destination_airport, airplane_name, airplane_type, maximum_distance, base_weight, current_weight, maximum_fuel, current_fuel, maximum_passengers, current_passengers, maximum_speed, average_fuel_consumption, crew_members, passengers)>
			<!ELEMENT airplane_id (#PCDATA)>
			<!ELEMENT destination_airport (#PCDATA)>
			<!ELEMENT airplane_name (#PCDATA)>
			<!ELEMENT airplane_type (#PCDATA)>
				<!ATTLIST airplane_type type (LightJet | MidSizeJet | JumboJet) "LightJet">
			<!ELEMENT maximum_distance (#PCDATA)>
			<!ELEMENT base_weight (#PCDATA)>
			<!ELEMENT current_weight (#PCDATA)>
			<!ELEMENT maximum_fuel (#PCDATA)>
			<!ELEMENT current_fuel (#PCDATA)>
			<!ELEMENT maximum_passengers (#PCDATA)>
			<!ELEMENT current_passengers (#PCDATA)>
			<!ELEMENT maximum_speed (#PCDATA)>
			<!ELEMENT average_fuel_consumption (#PCDATA)>
			<!ELEMENT crew_members (crew_member+)>
				<!ELEMENT crew_member (person_id, person_first_name, person_last_name, person_date_of_birth, person_age, person_weight, crew_member_type, crew_member_luggage?)>
					<!ELEMENT crew_member_type (#PCDATA)>
						<!ATTLIST crew_member_type type (Pilot | Stewardess) "Pilot">
					<!ELEMENT crew_member_luggage (id, contents, weight)>
						<!ELEMENT id (#PCDATA)>
						<!ELEMENT contents (#PCDATA)>
						<!ELEMENT weight (#PCDATA)>
			<!ELEMENT passengers (passenger+)>
				<!ELEMENT passenger (person_id, person_first_name, person_last_name, person_date_of_birth, person_age, person_weight, passenger_luggage?, passenger_ticket)>
					<!ELEMENT passenger_luggage (id, contents, weight)>
					<!ELEMENT passenger_ticket (ticket_id, ticket_destination, ticket_seat)>
						<!ELEMENT ticket_id (#PCDATA)>
						<!ELEMENT ticket_destination (#PCDATA)>
						<!ELEMENT ticket_seat (#PCDATA)>

=== Durengo/durlibjava/domain-hibernate-mapped/src/test/resources/main_example.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE airport SYSTEM "airport.dtd">
<airport>
    <airport_id>1</airport_id>
    <airport_name>Waterbury Airport</airport_name>
    <airport_size>SmallAirport</airport_size>
    <airport_latitude>-18.1332</airport_latitude>
    <airport_longitude>-27.2473</airport_longitude>
    <airport_country>Waterbury</airport_country>
    <airport_city>Haiti</airport_city>
    <airport_traffic_control_tower>
        <traffic_control_tower_id>2</traffic_control_tower_id>
        <traffic_control_tower_airspace>
            <airspace_id>3</airspace_id>
            <airspace_radius>1000.0</airspace_radius>
            <airspace_airspace_class>ClassDelta</airspace_airspace_class>
            <airspace_airplanes_in_vicinity>0</airspace_airplanes_in_vicinity>
        </traffic_control_tower_airspace>
        <traffic_control_tower_runways>
            <traffic_control_tower_runway>
                <runway_id>5</runway_id>
                <runway_length>400.0</runway_length>
                <runway_width>150.0</runway_width>
            </traffic_control_tower_runway>
        </traffic_control_tower_runways>
        <traffic_control_tower_telemetries>
            <traffic_control_tower_telemetry>
                <telemetry_id>6</telemetry_id>
                <telemetry_date_time>2023-03-11T19:26:50.848+02:00</telemetry_date_time>
                <telemetry_area>100.0</telemetry_area>
                <telemetry_temperature>32.0</telemetry_temperature>
                <telemetry_wind_speed>5.0</telemetry_wind_speed>
                <telemetry_humidity>30.0</telemetry_humidity>
                <telemetry_local_atmospheric_pressure>80.0</telemetry_local_atmospheric_pressure>
            </traffic_control_tower_telemetry>
        </traffic_control_tower_telemetries>
        <traffic_control_tower_control_tower_operators>
            <traffic_control_tower_control_tower_operator>
                <person_id>4</person_id>
                <person_first_name>Oper</person_first_name>
                <person_last_name>Ator</person_last_name>
                <person_date_of_birth>1970-06-10</person_date_of_birth>
                <person_age>53</person_age>
                <person_weight>70.0</person_weight>
            </traffic_control_tower_control_tower_operator>
        </traffic_control_tower_control_tower_operators>
    </airport_traffic_control_tower>
    <airplanes>
        <airplane>
            <airplane_id>7</airplane_id>
            <destination_airport>Lebanon</destination_airport>
            <airplane_name>Light Jet</airplane_name>
            <airplane_type>LightJet</airplane_type>
            <maximum_distance>3723.0</maximum_distance>
            <base_weight>5253.0</base_weight>
            <current_weight>5253.0</current_weight>
            <maximum_fuel>2428.0</maximum_fuel>
            <current_fuel>0.0</current_fuel>
            <maximum_passengers>9</maximum_passengers>
            <current_passengers>3</current_passengers>
            <maximum_speed>838.0</maximum_speed>
            <average_fuel_consumption>567.0</average_fuel_consumption>
            <crew_members>
                <crew_member>
                    <person_id>8</person_id>
                    <person_first_name>Cap</person_first_name>
                    <person_last_name>Capn</person_last_name>
                    <person_date_of_birth>1980-02-01</person_date_of_birth>
                    <person_age>43</person_age>
                    <person_weight>80.0</person_weight>
                    <crew_member_type>Pilot</crew_member_type>
                </crew_member>
            </crew_members>
            <passengers>
                <passenger>
                    <person_id>9</person_id>
                    <person_first_name>Seb</person_first_name>
                    <person_last_name>Ter</person_last_name>
                    <person_date_of_birth>2000-03-23</person_date_of_birth>
                    <person_age>23</person_age>
                    <person_weight>100.0</person_weight>
                    <passenger_luggage>
                        <id>10</id>
                        <contents>Toothbrush</contents>
                        <weight>5.0</weight>
                    </passenger_luggage>
                    <passenger_ticket>
                        <ticket_id>11</ticket_id>
                        <ticket_destination>Lebanon</ticket_destination>
                        <ticket_seat>1</ticket_seat>
                    </passenger_ticket>
                </passenger>
                <passenger>
                    <person_id>12</person_id>
                    <person_first_name>Sebas</person_first_name>
                    <person_last_name>Terme</person_last_name>
                    <person_date_of_birth>2000-03-23</person_date_of_birth>
                    <person_age>23</person_age>
                    <person_weight>100.0</person_weight>
                    <passenger_luggage>
                        <id>13</id>
                        <contents>Bat</contents>
                        <weight>3.0</weight>
                    </passenger_luggage>
                    <passenger_ticket>
                        <ticket_id>14</ticket_id>
                        <ticket_destination>Lebanon</ticket_destination>
                        <ticket_seat>2</ticket_seat>
                    </passenger_ticket>
                </passenger>
            </passengers>
        </airplane>
        <airplane>
            <airplane_id>15</airplane_id>
            <destination_airport>America</destination_airport>
            <airplane_name>Jumbo Jet</airplane_name>
            <airplane_type>JumboJet</airplane_type>
            <maximum_distance>14430.0</maximum_distance>
            <base_weight>190000.0</base_weight>
            <current_weight>190000.0</current_weight>
            <maximum_fuel>243400.0</maximum_fuel>
            <current_fuel>0.0</current_fuel>
            <maximum_passengers>660</maximum_passengers>
            <current_passengers>2</current_passengers>
            <maximum_speed>920.0</maximum_speed>
            <average_fuel_consumption>10230.0</average_fuel_consumption>
            <crew_members>
                <crew_member>
                    <person_id>16</person_id>
                    <person_first_name>Cap</person_first_name>
                    <person_last_name>Capn</person_last_name>
                    <person_date_of_birth>1980-02-01</person_date_of_birth>
                    <person_age>43</person_age>
                    <person_weight>80.0</person_weight>
                    <crew_member_type>Pilot</crew_member_type>
                </crew_member>
            </crew_members>
            <passengers>
                <passenger>
                    <person_id>17</person_id>
                    <person_first_name>Sebas</person_first_name>
                    <person_last_name>Terme</person_last_name>
                    <person_date_of_birth>2000-03-23</person_date_of_birth>
                    <person_age>23</person_age>
                    <person_weight>100.0</person_weight>
                    <passenger_luggage>
                        <id>13</id>
                        <contents>Bat</contents>
                        <weight>3.0</weight>
                    </passenger_luggage>
                    <passenger_ticket>
                        <ticket_id>18</ticket_id>
                        <ticket_destination>America</ticket_destination>
                        <ticket_seat>0</ticket_seat>
                    </passenger_ticket>
                </passenger>
            </passengers>
        </airplane>
    </airplanes>
</airport>
